Modify: テスコードを有効化
shzxcv/rspec_app_exam pull request #1
Opened 2020-10-27 07:28 UTC by sho171

確認をお願いします。

2020-10-27 10:16 UTC, yuji91 requested changes

2020-10-27 10:16 UTC, yuji91 commented on spec/factories/tasks.rb
> +      status { "done" }
enumで定義した値はStringではなくSymbolで記載しましょう。これにより、該当のカラムがenumを使用していることが伝わります。
```suggestion
      status { :done }
```

2020-10-27 10:16 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to have_content(Time.current.strftime('%m/%d %H:%M'))
`strftime`の中を変えることでテストは通りますが、今後Viewで使用しているメソッドの仕様が変わるとテストが落ちてしまうので、Viewで使われているメソッドを読み込んで使う様にしましょう！

2020-10-27 10:16 UTC, yuji91 commented on spec/system/task_spec.rb
> +        task = FactoryBot.create(:task, :done, project_id: project.id)
`FactoryBot.`の部分は設定ファイルに追記を行って省略した方がコード量が減るので良いですね。
```suggestion
        task = create(:task, :done, project_id: project.id)
```

2020-10-28 00:28 UTC, sho171 commented on spec/factories/tasks.rb
> +      status { "done" }
修正しました。

2020-10-28 00:43 UTC, sho171 commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to have_content(Time.current.strftime('%m/%d %H:%M'))
ApplicationHelperをincludeして、short_timeメソッドを使用するように変更しました。

2020-10-28 00:44 UTC, sho171 commented on spec/system/task_spec.rb
> +        task = FactoryBot.create(:task, :done, project_id: project.id)
修正しました。

2020-10-28 03:28 UTC, yuji91 approved these changes
少し細かい点ですが、レビューの修正は指摘事項の内容毎にコミットの単位を分けられるとレビュアーが確認しやすくなりますね。

コミットIDはリンクとしても機能するので、「22c623a で修正しました。」と言う形で各指摘事項にコメントで返信するのが一番見やすくなるかと思います。

例として、自分では以下のようにコミットを分けてメッセージを記載します。
```
Fix: enumの値をStringからSymbolに変更
Fix: Viewで使用しているhelperを使用
Fix: FactoryBotの定義を省略
```

GitHubでレビューする課題はこれで完了なので、また機会があれば参考にして頂ければと思います。
また、この辺りをどこまで細かく対応するかは、入った現場に合わせて頂ければ良いと思います。

修正の内容自体は全く問題ないので、応用編に進んで頂いて大丈夫です！

2020-10-28 05:37 UTC, sho171 commented
イトウさん
コメントありがとうございました。
納得しました、コミット単位でdiffできてレビューワーにとってメリットが大きそうですね。
ポートフォリオ作成の際に、自分でも確認しやすいように意味のあるコミット単位、コミットのコメントを心がけます！

2020-10-28 05:37 UTC, merged